name = "Create SMP Modpack"
author = "memz1013 (Ezilith)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "647d457f521e9b7073e0043e17b9afbe04829d1297d7e1e2e988427a54440b3a"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
