DEFAULTRANGE = [-0.6, 2.1]
ACACIARANGE = [1.7, 2.2]
AZALEASRANGE = [0.4, 1.8]
BIRCHRANGE = [0.15, 0.8]
CHERRYRANGE = [0.3, 0.55]
DARKOAKRANGE = [0.65, 0.8]
JUNGLERANGE = [0.85, 1.95]
MANGROVERANGE = [0.65, 0.9]
OAKRANGE = [0.15, 2.1]
SPRUCERANGE = [-0.75, 0.35]
